[package]
name = "cli-rs-command-gen"
version = "0.1.12"
edition = "2021"
description = "internal helper for cli-rs"
license = "Unlicense"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
